### ISSUE TITLE
[FEATURE] Rangübersicht

### ISSUE THREAD

**Issue by Keviro** [Keviro/community-server-docs#25]
Eine Rangübersicht in der Dokumentation wäre sinnvoll. Sie sollte alle aktuellen Ränge, deren Funktion, sowie die Bedingungen zum Erhalt des Ranges auflisten. Es wäre also super, wenn irgendwer die Zeit findet, dies zu implementieren.

Folgende Informationen kann ich dafür schon einmal bereitstellen. Bitte nicht 1 zu 1 übernehmen, sondern übersichtlich ausarbeiten. Ggf. fehlt auch noch etwas an Informationen. Da wäre es super diese dann noch zu ergänzen. Kommt gerne auch in den TeamSpeak um bezüglich der Ausarbeitung Rücksprache zu halten.

--------------------

Aktuell gibt es folgende Ränge:

**Teamränge:**
- Management (Verwaltung der Infrastruktur, Entwicklung von Plugins, Teammanagement)
- Administrator (Ansprechpartner bei Bugreports / Erstattungen; Entwicklung von Plugins) 
- Developer (Unterstützt uns bei der Entwicklung des Servers und oder Events)
- Moderator (Ebenfalls Ansprechpartner bei Fragen, jedoch auch bezüglich der Regeln und dessen Auslegung; Übernimmt moderative Aufgaben, wie das Durchsetzen der Regeln)
- Supporter (Ansprechpartner für Fragen bezüglich Funktionen/Features des Servers etc)
- Builder (Hilft beim Bauen von Maps für z.B. Events oder andere Server Bereiche)

Theoretisch kann sich jeder auf den Rang Builder, Supporter und Developer bewerben, indem er sich bei uns meldet. Eine Bewerbung als Moderator, Administrator oder Management ist nicht möglich.

Was Builder und Supporter betrifft, machen wir jedoch in der Regel einen Aufruf, sobald wir Teammitglieder suchen oder kommen aktiv auf Spieler zu, welche uns positiv aufgefallen sind. Eine direkte Bewerbung auf den Moderator Rang ist nicht möglich, man kann nur von Supporter aufsteigen.

Die Anforderungen für Developer sind recht hoch. Bitte bewerbt euch nur, wenn ihr genügend Erfahrung und Lust und Zeit für das Projekt habt. Bewerber sollten sich mit Gradle, Git, Spring, MySQL und Redis auskennen und es sollten bereits Erfahrungen in der Entwicklung von Paper und Velocity Plugins vorhanden sein. Asynchrone Programmierung und die Arbeit mit Packets bzw. PacketEvents sollte kein Problem darstellen.

Teammitglieder müssen außerdem TeamSpeak und ShadowPlay bzw. Radeon ReLive besitzen und regelmäßig auf dem server und TeamSpeak aktiv sein.

**Spieler Ränge:**
- Contributor (Verteilt an ehemalige Teammitglieder oder Spieler die uns auf andere Weise sehr geholfen haben)
- Veteran (Verteilt an alle Spieler, welche auf dem 1.19 Server mehr als 200 Stunden aktive Spielzeit hatten)
- Spieler (Der normale Rang für jeden neuen Spieler)

Die aktuellen Ranggrafiken sind hier zu finden: https://drive.google.com/file/d/1FxZxgp-7-3c4kR3CZsGCVe_WsMMCxzp4/view

**Comment by JoField08** [comment]
Twisti hast du da schon was gemacht oder soll ich mich da mal ran setzen?

**Comment by JoField08** [comment]
Ja also kann man das so machen oder muss da was anderst?
