### ISSUE TITLE
[FEATURE] Herkunft der Enchantments

### ISSUE THREAD

**Issue by Keviro** [Keviro/community-server-docs#26]
Es wäre sinnvoll in der Dokumentation über die Custom Enchantments ebenfalls hinzuzufügen, wie man das betreffende Enchantment bekommen kann. Heißt:

- **Replenish** (discoverable: true, enchantable: true)
- **Telekinesis** (discoverable: true, enchantable: true)
- **Experience** (discoverable: true, enchantable: true)
- **Beheading** (discoverable: true, enchantable: true)
- **Silent Gaze** (discoverable: true, enchantable: true)
- **Soulbound** (discoverable: true, enchantable: false)
- **Rocket Saver** (discoverable: false, enchantable: false)

```
discoverable = If the enchantment can be found in chests and loot tables.
enchantable: If the enchantment can be obtained from enchanting tables.
```

**Comment by TheBjoRedCraft** [comment]
https://github.com/Keviro/community-server-docs/pull/45
