### ISSUE TITLE
/phead unter Köpfe und Rüstungsständer

### ISSUE THREAD

**Issue by SasaBrix** [Keviro/community-server-docs#28]
Das fehlt leider noch. Unsere Spieler können es also nicht nachschauen und sind dann so doof und schauen unter /hdb. Das bitte noch hinzufügen :)

**Comment by JoField08** [comment]
https://server.castcrafter.de/commands.html#chat-und-textnachrichten

**Comment by Keviro** [comment]
Es geht um: https://server.castcrafter.de/cosmetics.html

**Comment by JoField08** [comment]
Achso, ja das kann man ja unter see also packen oder? 👍
