### ISSUE TITLE
Für das Bau-Event: Dürfen wir/wäre es möglich einzurichten, das wir Axiom nutzen können?

### ISSUE THREAD

**Issue by TheBjoRedCraft** [Keviro/community-server-docs#44]
Für das Bau-Event: Dürfen wir/wäre es möglich einzurichten, das wir Axiom nutzen können?

**Comment by Keviro** [comment]
Ist aktuell nicht geplant. Für die Nutzung auf Servern ist für Axiom entweder eine Whitelist für jeden einzelnen User erforderlich oder wir müssten die Lizenzgebühren tragen. Außerdem können mit Axiom einfach Schematics eingefügt werden. Das wollen wir nicht. Die Bewerber sollen selber etwas bauen und keine Schematic pasten. Spieler mit Axiom Whitelist hätten dann einen unfairen Vorteil gegenüber anderen. Auch aus technischer Perspektive hat Axiom nur `Preliminary PlotSquared support (tested locally, but hasn't been used in production yet)` und noch keine ausgereifte Unterstützung.
